### ISSUE TITLE
[win10] script times out and does nothing

### ISSUE THREAD

**Issue by CrewMonk33** [Arthur-K-99/szurubooru-grabber-script#1]
On windows 10, filles the option boxes the way that was indicated, installed all that was needed with pip, but when I try to save with grabber, the thing freezes for like 30 seconds and then timeouts. This is what the grabber logs give me :
`[01:24:42.275][Error] Command execution timeout
[01:24:42.276][Warning] [Qt][default] QProcess: Destroyed while process ("python") is still running.`

**Comment by Arthur-K-99** [comment]
Can't reproduce on my end. Just tried with a fresh install. Seems like it is outside the scope of the script, either Grabber or your python implementation.
